@startuml Diagrama de actividad

start
if (usuario existente) then (sí)
    :iniciar sesión;
else (no)
    :registrarse;
endif
switch(acción)
case ()
:Crear cuenta;
case ()
:Sacar dinero;
case ()
:Ingresar dinero;
case()
:Hacer bizum;
:confirmar;
endswitch
stop

@enduml